---

- name: "Copy backend built files"
  copy:
    src: "{{ playbook_dir }}/../../backend/dist/"
    dest: ~/project

- name: "Start backend server with pm2"
  shell: |
    env
    pm2 start ~/project/main.js -f